name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Test Build Process
        run: npm run build

      - name: Cache Build Artifacts
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

  deploy:
    environment: main
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy via SSH
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
            export NVM_DIR=/home/${{ secrets.SSH_USERNAME }}/.nvm
            source /home/${{ secrets.SSH_USERNAME }}/.nvm/nvm.sh
            cd ${{ secrets.PATH }}
            git reset --hard
            git pull origin main
            npm ci
            npm run build
          EOF

          rm -f private_key.pem
